### ISSUE TITLE
checksecurity_2.0.15

### ISSUE THREAD

**Issue by orascheg** [ni/meta-security#10]
The package checksecurity_2.0.15.bb is not available anymore at http://ftp.de.debian.org/debian/pool/main/c/checksecurity/

Only 2.0.16 is on the server.

**Comment by amstewart** [comment]
Hey @orascheg. It looks like `checksecurity` isn't a dependency of any NI software - or at least it isn't listed as such. And so it is only being built into the extras/ packagefeed, which we normally allow to fail.

Is `checksecurity` a requirement for something you're working on?

**Comment by orascheg** [comment]
II have been building the packagegroup packagegroup-security-scanners and got errors at building. I am not deep enough into the meta layer to tell if this is an NI dependency or not. I changed the recipe and was able to build then.

 BTW also the defined version of clamav is not supported anymore:
Fri Aug 11 12:20:23 2023 -> ^Your ClamAV installation is OUTDATED!
Fri Aug 11 12:20:23 2023 -> ^Local version: 0.101.5 Recommended version: 0.103.8
Fri Aug 11 12:20:23 2023 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav

**Comment by amstewart** [comment]
`packagegroup-core-security` is one which we only build as a part of the extras/ feed. If you don't actually need it for your solution, you can run bitbake with the `-k` flag to ignore failing recipes - which is what we do when we build that feed.

We include a lot of layers from the community, but we only guarantee the recipes which are real dependencies of NI workflows. If you need these meta-security packages as a part of an NI HW/SW stack deployment, let me know and we can consider how to work them into the support envelope. In the mean time, I'll close this issue as unsupported.
