### ISSUE TITLE
meta-security dunfell fails to produce FAPI files

### ISSUE THREAD

**Issue by kuldeepmarker-eaton** [ni/meta-security#5]
HI All,

I have used meta-security as a layer and I intend to make use of the meta-tpm. I am able to build properly using yocto but I am not seeing FAPI related files when tpm-tss recipe is build. I can see that ESYS API and SAPI files are there in the build folder of tpm2-tss. So what is needed to generate FAPI files

**Comment by amstewart** [comment]
Hey @kuldeepmarker-eaton,

NI doesn't actually use the `meta-tpm` sub-layer within meta-security in our NI LinuxRT builds. So we don't have expertise in how the `tpm2-tss` recipe within that layer is designed.

I see you opened a [similar issue](https://github.com/jiazhang0/meta-secure-core/issues/246) in meta-secure-core. Are you trying to integrate TPM2 user-space tools into an NI LinuxRT deployment, or into your own OE distribution? If the former, I'd be happy to talk about your use-case and get an understanding of your requirements.

Either way, you might want to open an issue with the meta-security upstream maintainers on [the yocto mailing list](https://lists.yoctoproject.org/g/yocto) \<<yocto@lists.yoctoproject.org>\>. It seems that the yocto project has expected the FAPI configuration switch for `tpm2-tss` [to work](https://git.yoctoproject.org/meta-security/commit/meta-tpm/recipes-tpm2/tpm2-tss?id=696651d0c32258b789ab768bb506bc0a1fdc9a31) at some point in the past.

**Comment by kuldeepmarker-eaton** [comment]
HI @amstewart ,

Thanks for a quick reply. I am trying to integrate TPM2 user space tools into ST Openstlinux distro. And I want to use FAPI API to interact with TPM. I will create an issue regarding this.

**Comment by amstewart** [comment]
Ah; I see. The yocto mailing list is probably your best bet for an answer then.

I'll go ahead and close this issue. Let me know if you have any objections.
